apiVersion: v1
kind: Service
metadata:
  name: eep-service
  namespace: default
  labels:
    app: eep
spec:
  selector:
    app: eep
  ports:
    - protocol: TCP
      port: 80              # External port (Ingress/browser will hit this)
      targetPort: 8501      # Internal Streamlit app port
  type: LoadBalancer
