apiVersion: apps/v1
kind: Deployment
metadata:
  name: eep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eep
  template:
    metadata:
      labels:
        app: eep
    spec:
      containers:
      - name: eep
        image: trainmeaiacr.azurecr.io/eep:latest
        ports:
          - containerPort: 8501
        env:
        - name: IEP1_URL
          valueFrom:
            configMapKeyRef:
              name: eep-config
              key: IEP1_URL
        - name: IEP2_URL
          valueFrom:
            configMapKeyRef:
              name: eep-config
              key: IEP2_URL
        - name: IEP3_URL
          valueFrom:
            configMapKeyRef:
              name: eep-config
              key: IEP3_URL
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: eep-config
              key: APP_MODE
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: eep-secret
              key: DATABASE_URL
