apiVersion: apps/v1
kind: Deployment
metadata:
  name: iep-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iep-1
  template:
    metadata:
      labels:
        app: iep-1
    spec:
      containers:
        - name: iep-1
          image: trainmeaiacr.azurecr.io/iep-1
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: iep1-secret
                  key: DATABASE_URL
